name: widget-draughts 
base: core18 
version: '1.0.1' 
summary: Widget Draughts is a computer draughts game for Linux.
description: |
  Widget Draughts is a computer draughts game for Linux written using C++ and wxWidgets. 
  With Widget Draughts you play against the computer. The human player is black and the computer is white. 
  Upstream: https://github.com/crispinalan/widget-draughts 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


apps:
  widget-draughts:
    adapter: full
    command: usr/local/wxdraughts
    extensions: [gnome-3-28]
    plugs:
    - x11
    - wayland
    - desktop
    - desktop-legacy
    
    


parts:
  desktop-gtk3:
  wxwidgets-3-0-gtk3:

parts:
  widget-draughts:
    # See 'snapcraft plugins'    
    source: https://github.com/crispinalan/widget-draughts.git
    source-type: git
    source-branch: master
    plugin: cmake
    configflags:
       - -DCMAKE_INSTALL_PREFIX=/usr/local
    after:
       - wxwidgets-sdk       
    stage-packages:
      - libgtk-3-0
      - libgl1
      - libglvnd0
      - libglx0
      - libice6
      - libnotify4
      - libsm6
      - libxxf86vm1
      - libcanberra-gtk3-module
      - gettext
    build-packages:  
      - gcc
      - g++
      - make     
      - libwxgtk3.0-dev
      - libgtk-3-dev
      - git
     
  # The wxWidgets SDK Stage Snaps
  # https://forum.snapcraft.io/t/the-wxwidgets-sdk-stage-snaps/10877
  wxwidgets-sdk:
    plugin: nil
    stage-snaps:
    - wxwidgets-sdk-gtk3
    stage-packages:
    # Crash dialog support
    - binutils
    filesets:
      crash-dialog-support:
      - usr/bin/*addr2line
      library-shared:
      - '**/lib/**/*.so*'
    prime:
    - $crash-dialog-support
    - $library-shared
    


