name: widget-draughts 
base: core18 # the base snap is the execution environment for this snap
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Widget Draughts is a computer draughts game for Linux. # 79 char long summary
description: |
  Widget Draughts is a computer draughts game for Linux written using C++ and wxWidgets. 
  With Widget Draughts you play against the computer. The human player is black and the computer is white. 
  Upstream: https://github.com/crispinalan/widget-draughts 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


apps:
  widget-draughts:
    adapter: full
    command: usr/local/wxdraughts
    extensions: [gnome-3-28]
    #command-chain:
      #- usr/local/desktop-launch


parts:
  desktop-gtk3:
  wxwidgets-3-0-gtk3:

parts:
  widget-draughts:
    # See 'snapcraft plugins'    
    source: https://github.com/crispinalan/widget-draughts.git
    source-type: git
    source-branch: master
    plugin: cmake
    configflags:
       - -DCMAKE_INSTALL_PREFIX=/usr/local
    after:
       - wxwidgets-sdk       
    stage-packages:
      - libgtk-3-0
      - libgl1
      - libglvnd0
      - libglx0
      - libice6
      - libnotify4
      - libsm6
      - libxxf86vm1
      - libcanberra-gtk3-module
      - gettext
    build-packages:  
      - gcc
      - g++
      - make     
      - libwxgtk3.0-dev
      - libgtk-3-dev
      - git
     
 # to do
 # wxWidgets SDK stage
 # plugs for strict


